on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check and Update Version
        id: update_version
        run: |
          TAG_NAME=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)

          VERSION=${TAG_NAME#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          {
            echo "MAJOR=$MAJOR"
            echo "MINOR=$MINOR"
            echo "PATCH=$PATCH"
          } > versions.env

          echo "CADDY_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "CADDY_VERSION=$VERSION" > versions.env

      - name: Commit
        run: |
          git config --global user.name 'Md. Touhidur Rahman'
          git config --global user.email 'touhidurrr@pm.me'
          git add versions.env
          git commit -m "Update Caddy Version to ${{ steps.update_version.outputs.CADDY_VERSION }}"
          git push
